### ISSUE TITLE
WIFI continuously disconnecting when using sta+ap wifi mode

### ISSUE THREAD

**Issue by gnkarn** [marvinroger/async-mqtt-client#124] opened 2018-12-15 00:04 UTC
as i was not able found a single working case where the esp is actin as sta  on mqtt , and as of AP using UDP, i have the doubt if it is something wrong in the code or if this si not possible to implement as of today.

in my case i have , a master esp and a slave esp
master is STA+AP , and slave is STA only 
slave has no problems , but master is totally unreliable due to wifi continuous dropping and reconnecting .

` // https://github.com/hansjny/Natural-Nerd/blob/master/arduino/soundsread2/sound_reactive.ino
// version async mqtt
#include <FastLED.h>
#include <ESP8266WiFi.h>
//#include <WiFiUDP.h>
#include "reactive_common.h"

#include <DNSServer.h>            //Local DNS Server used for redirecting all requests to the configuration portal
//#include <ESP8266WebServer.h>     //Local WebServer used to serve the configuration portal
#include <ArduinoJson.h>
#define SENSORNAME "led_vertical"

/************ WIFI and MQTT Information (CHANGE THESE FOR YOUR SETUP) ******************/
//const char* ssid = "YourSSID"; //type your WIFI information inside the quotes
//const char* password = "YourWIFIpassword";
//#include <PubSubClient.h> // mqtt

const char* mqtt_username = "xxxxx";
const char* mqtt_password = "xxxx";
const char* mqtt_clientid = SENSORNAME;
#include <AsyncMqttClient.h>    //https://github.com/marvinroger/async-mqtt-client

/// for async mqtt
#define MQTT_HOST IPAddress(192, 168, 0, xx)
#define MQTT_PORT 1883
#include <Ticker.h> /// para leds de status
AsyncMqttClient mqttClient;
Ticker mqttReconnectTimer;

WiFiEventHandler wifiConnectHandler;
WiFiEventHandler wifiDisconnectHandler;
Ticker wifiReconnectTimer;
///

long lastReconnectAttempt = 0; // mqtt sta reconnect
bool stateOn = false;
int transitionTime = 0;
#define BRIGHTNESS  200// set master brightness 0-255 here to adjust power consumption
byte red = 255;
byte green = 255;
byte blue = 255;
byte brightness = 255;
byte myBrightness = BRIGHTNESS;  // global brightness changable from screen
/************* MQTT TOPICS (change these topics as you wish)  **************************/
const char* led_vertical_state_topic = "led_vertical/stat"; // no los uso?
const char* led_vertical_set_topic = "led_vertical/cmnd";

const char* on_cmd = "ON";
const char* off_cmd = "OFF";
const char* effect = "solid";
String effectString = "solid";
String oldeffectString = "solid";

// MSGEQ7 wiring on spectrum analyser shield ********************************
#define MSGEQ7_STROBE_PIN D2//antes 2
#define MSGEQ7_RESET_PIN  D6// antes 1
#define AUDIO_LEFT_PIN    0
#define AUDIO_RIGHT_PIN   0
// storage of the 7 10Bit (0-1023) audio band values
// modified only by AudioRead()
int left[7];
int right[7];
/****************************************FOR JSON***************************************/
// Step 1: DEfinir Json buffer :Reserve memory space
const int BUFFER_SIZE = JSON_OBJECT_SIZE(10);
#define MQTT_MAX_PACKET_SIZE 512

// fin setup mqtt **********************FOR JSON***************************************/

// https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/examples/ESP_AsyncFSBrowser/ESP_AsyncFSBrowser.ino
//#include <ArduinoOTA.h>
//#include <ESP8266mDNS.h>
#include <FS.h>

const char *OTAName = "sound_master_ota";           // A name and a password for the OTA service
const char *OTAPassword = "xxxx";

File fsUploadFile;                                    /// a File variable to temporarily store the received file

///remote debug
///#include "RemoteDebug.h" //https://github.com/JoaoLopesF/RemoteDebug
#ifdef REMOTE_DEBUG
RemoteDebug Debug;
#define DBG_OUTPUT_PORT Debug
#else
#define DBG_OUTPUT_PORT Serial
#endif
/// end remote debug

#define LED_BUILTIN 16 /// el led rojo del nodemcu

#define D0 16 //Reset button ,  y posible blue led
#define D1 5 // I2C Bus SCL (clock)
#define D2 4 // I2C Bus SDA (data)
#define D3 0 //FLASH button
#define D4 2 // blue as "LED_BUILTIN"
#define D5 14 // SPI Bus SCK (clock)
#define D6 12 // SPI Bus MISO
#define D7 13 // SPI Bus MOSI
#define D8 15 // SPI Bus SS (CS)
#define D9 3 // RX0 (Serial console)
#define D10 1 // TX0 (Serial console)

#define LED_AZUL D4 //GPIO02

#define READ_PIN 0 //
#define BUTTON_PIN D3 // para prueba uso el flash button

#define NUMBER_OF_CLIENTS 1 // 1 a 4

const int checkDelay = 5000;
const int buttonDoubleTapDelay = 200;
const int numOpModes = 5;

unsigned long lastChecked;
unsigned long buttonChecked;
bool buttonClicked = false;
bool queueDouble = false;
bool clickTrigger;
bool doubleTapped;
WiFiUDP UDP;

struct led_command {
        uint8_t opmode;
        uint32_t data;
};

bool heartbeats[NUMBER_OF_CLIENTS];

static int opMode = 1;

IPAddress sta_staticIP(192,168,0,xx);// ip para led_lamp master STAtion
IPAddress sta_gateway(192,168,0,xx);
IPAddress sta_subnet(255,255,255,0);

/*__________________________________________________________SETUP_FUNCTIONS__________________________________________________________*/
// ***************************************************************************
// Load library "ticker" for blinking status led
// ***************************************************************************
Ticker ticker;
void tick() {
        int state = digitalRead(LED_BUILTIN); // get the current state of GPIO1 pin
        digitalWrite(LED_BUILTIN, !state); // set pin to the opposite state
}
/// end Ticker

void startSPIFFS() { // Start the SPIFFS and list all contents
        SPIFFS.begin();                       // Start the SPI Flash File System (SPIFFS)
        Serial.println("SPIFFS started. Contents:");
        {
                Dir dir = SPIFFS.openDir("/");
                while (dir.next()) {          // List the file system contents
                        String fileName = dir.fileName();
                        size_t fileSize = dir.fileSize();
                        Serial.printf("\tFS File: %s, size: %s\r\n", fileName.c_str(), formatBytes(fileSize).c_str());
                }
                Serial.printf("\n");
        }
}
/// end ota

/*__________________________________________________________efectos__________________________________________________________*/
// List of patterns to cycle through.  Each is defined as a separate function below.
// Each pattern is defined as a function that takes two uint8_t's; all of the pattern functions
// have to have the same signature in this setup, and two (hardcoded!) parameters can be
// passed to each one: ( mark kriesgman demo reel arg2)
typedef void (*TwoArgumentPattern)(uint8_t arg1, uint8_t arg2);
typedef struct {
        TwoArgumentPattern mPattern; // nombre de la funcion a llamar
        String mName;   // nombre que se mostrara del efecto
        uint8_t mArg1;
        uint8_t mArg2;
} TwoArgumentPatterWithArgumentValues;

TwoArgumentPatterWithArgumentValues gPatternsAndArguments[] = {
        { LedsNoise,"LedsNoise", 0 /* nada*/,0 /* nada1*/ },  //32
        { Dots1,"Dots1",   1 /*color1 */, 1 /*color2 */ },
        { Dots2,"Dots2",   125 /*scale*/, 0 /*no se usa*/}

        //las funciones de  demoreel 100 adaptarlas para matriz e incluir
};

/*__________________________________________________________SETUP__________________________________________________________*/
void setup()
{
        Serial.setDebugOutput(true);  //habilita debug , para wifi

        pinMode(READ_PIN, INPUT);
        pinMode(BUTTON_PIN, INPUT );
        pinMode(LED_AZUL, OUTPUT);
        pinMode(LED_BUILTIN, OUTPUT);
        pinMode(MSGEQ7_STROBE_PIN, OUTPUT);// strobe pin as output
        pinMode(MSGEQ7_RESET_PIN, OUTPUT);// reset  pin as output

        Serial.begin(115200);
        Serial.println();
        Serial.print("led master iniciado ... ");

        const char *hostname_wm = "led_master_wmAP";

        InitMSGEQ7();

        // prepara SoftAP led lamp -------------------------------------------------
        ticker.attach(0.5, tick);
        const char *hostname_ap = "led_master_AP";
        const char *pass_ap = "xxxx";

        Serial.println("IP address: ");
        Serial.println(WiFi.localIP());
        Serial.println("Setting lamp AP");
        WiFi.mode(WIFI_AP_STA); // debe estar ?
        // WiFi.softAP(ssid, password, channel, hidden, max_connection)
        Serial.println(WiFi.softAP(hostname_ap, pass_ap,8, 0,2) ? "Ready" : "Failed!");  // setea soft AP en wifi.channel()=8
        Serial.println("wifi channel = ");
        Serial.println(WiFi.channel());

        Serial.print("Soft-AP IP address = ");
        Serial.println(WiFi.softAPIP());
        Serial.print("local IP address = ");
        Serial.println(WiFi.localIP());
        WiFi.printDiag(Serial);
        ticker.detach();

        // WiFi.persistent(false);
        // WiFi.mode(WIFI_AP);
        // WiFi.softAP("sound_reactive", "xxxxxxx");
        // Serial.print("Soft-AP IP address = ");
        // Serial.println(WiFi.softAPIP());
        Serial.setDebugOutput(true);//
        if (UDP.begin(7171)) { Serial.println(" esperando UDP en port 7171");};// listening on this port
        resetHeartBeats();

        //-------------- mqtt setup
        WiFi.config(sta_staticIP, sta_gateway, sta_subnet);//

        wifiConnectHandler = WiFi.onStationModeGotIP(onWifiConnect);

        wifiDisconnectHandler = WiFi.onStationModeDisconnected(onWifiDisconnect);

        mqttClient.onConnect(onMqttConnect);
        mqttClient.onDisconnect(onMqttDisconnect);
        mqttClient.onSubscribe(onMqttSubscribe);
        mqttClient.onUnsubscribe(onMqttUnsubscribe);
        mqttClient.onMessage(onMqttMessage);
        mqttClient.onPublish(onMqttPublish);
        mqttClient.setServer(MQTT_HOST, MQTT_PORT);

        ticker.attach(0.2, tick);
        connectToWifi(); // ok
        while (WiFi.status() != WL_CONNECTED)
        {
                delay(500);
                Serial.print(".");
        }
        delay(2000);

        //waitForConnections();// eliminado para debug
        lastChecked = millis();
        buttonChecked = 0;
        // startMDNS();                 /// Start the mDNS responder
        //startServer();                /// Start a HTTP server with a file read handler and an upload handler

} //end setup

/*__________________________________________________________SERVER_HANDLERS__________________________________________________________*/

/*__________________________________________________________LOOP__________________________________________________________*/

void loop()
{ uint32_t analogRaw;
        //server.handleClient();                      /// run the server
        ReadAudio();

        buttonCheck();
        // cada checkDelay ms verifica Hb
        if (millis() - lastChecked > checkDelay) {
                Serial.print("wifi mode: ");//debug
                Serial.println(WiFi.getMode());//debug
                if (!checkHeartBeats()) {
                        waitForConnections(); // udp  connection nohb received for 5secs
                }
                lastChecked = millis();
        } else{
                //Serial.print("in switch : ");//debug

                switch (opMode) {
                case 1:

                        analogRaw=left[3]/4;
                        //for (int i = 0; i < 7; i++) {
                        //Pixel(i, 16 - left[i] / 64, left[i] / 4);
                        //}
                        sendLedData(analogRaw, opMode);
                        opMode=1;
                        break;
                case 2:
                        sendLedData(0, opMode);
                        //delay(10);
                        opMode=0;
                        break;
                case 3:
                        sendLedData(0, opMode);
                        opMode=0;
                        break;
                case 4:
                        sendLedData(0, opMode);
                        opMode=0;
                        break;
                //default:
                      //  Serial.print(".");
                }
                if(opMode >1) {Serial.print(opMode); }//debug
              //  if(opMode ==1) {Serial.println(analogRaw); }
        }

}

void sendLedData(uint32_t data, uint8_t op_mode)
{
        struct led_command send_data;
        send_data.opmode = op_mode;
        send_data.data = data;
        for (int i = 0; i < NUMBER_OF_CLIENTS; i++)
        {
                IPAddress ip(192,168,4,2 + i);
                UDP.beginPacket(ip, 7001); // CLIENTS IP
                UDP.write((char*)&send_data,sizeof(struct led_command));
                UDP.endPacket();
        }
      //  Serial.print("U");//debug
}

void waitForConnections() {
        digitalWrite(LED_BUILTIN, 1); // set pin on, apagado
        //ticker.attach(1, tick);// fast blinck while waiting for clients
        while(true) {
                // ojo de esta forma el programa queda bloqueado hasta recibir hb!!!
                readHeartBeat();
                if (checkHeartBeats()) {
                        return;
                }
                //delay(checkDelay);
                resetHeartBeats();
                //Serial.printf("Stations connected to soft-AP = %d\n", WiFi.softAPgetStationNum());// para debug ver estaciones conectadas al softap
        }
}

void resetHeartBeats() {
        for (int i = 0; i < NUMBER_OF_CLIENTS; i++) {
                heartbeats[i] = false;
        }
}

void readHeartBeat() {
        struct heartbeat_message hbm;
        while(true) {
                int packetSize = UDP.parsePacket();
                if (!packetSize) {
                        break;
                }
                UDP.read((char *)&hbm, sizeof(struct heartbeat_message));
                if (hbm.client_id > NUMBER_OF_CLIENTS) {
                        Serial.println("Error: invalid client_id received");
                        continue;
                }
                heartbeats[hbm.client_id - 1] = true;
                //Serial.printf("hb" );
        }
}

bool checkHeartBeats() {
        //sendState();// feedback para debug
        for (int i = 0; i < NUMBER_OF_CLIENTS; i++) {
                if (!heartbeats[i]) {
                        return false;
                }
        }
        resetHeartBeats();
        // enviar hb a mqtt
        digitalWrite(LED_BUILTIN, 0);         // set pin 0 turn on led
        return true;
}

void buttonCheck()
{
        int but = digitalRead(BUTTON_PIN);
        if (but == 0) {
                if (millis() - buttonChecked < buttonDoubleTapDelay && buttonClicked == false ) {
                        doubleClicked();
                        doubleTapped = true;
                }
                clickTrigger = true;
                buttonClicked = true;
                buttonChecked = millis();
        }

        else if (but == 1) {
                if (millis() - buttonChecked > buttonDoubleTapDelay && clickTrigger) {
                        if (!doubleTapped) {
                                clicked();
                        }
                        clickTrigger = false;
                        doubleTapped = false;
                }
                buttonClicked = false;
        }
}

void clicked() {
        if (opMode == numOpModes)
                opMode = 1;
        else
                opMode++;
        //  opMode=3;//debug
        Serial.printf("Setting opmode %d \n", opMode);
}

void doubleClicked() {
        Serial.printf("Stations connected to soft-AP = %d\n", WiFi.softAPgetStationNum());// para debug ver estaciones conectadas al softap

}

/*__________________________________________________________HELPER_FUNCTIONS__________________________________________________________*/

String formatBytes(size_t bytes) { // convert sizes in bytes to KB and MB
        if (bytes < 1024) {
                return String(bytes) + "B";
        } else if (bytes < (1024 * 1024)) {
                return String(bytes / 1024.0) + "KB";
        } else if (bytes < (1024 * 1024 * 1024)) {
                return String(bytes / 1024.0 / 1024.0) + "MB";
        }
}

String getContentType(String filename) { // determine the filetype of a given filename, based on the extension
        if (filename.endsWith(".html")) return "text/html";
        else if (filename.endsWith(".css")) return "text/css";
        else if (filename.endsWith(".js")) return "application/javascript";
        else if (filename.endsWith(".ico")) return "image/x-icon";
        else if (filename.endsWith(".gz")) return "application/x-gzip";
        return "text/plain";
}
/*__________________________________________________________definicion efectos_________________________________________________________*/
void LedsNoise (byte nada,byte nada1)
{
        opMode=1;
}

void Dots1 (byte nada,byte nada1){
        opMode=2;
}

void Dots2 (byte nada,byte nada1){
        opMode=4;
}

/*__________________________________________________________definicion MSGEQ7*/
void InitMSGEQ7() {
        pinMode(MSGEQ7_RESET_PIN, OUTPUT);
        pinMode(MSGEQ7_STROBE_PIN, OUTPUT);
        digitalWrite(MSGEQ7_RESET_PIN, LOW);
        digitalWrite(MSGEQ7_STROBE_PIN, HIGH);
}

// get the data from the MSGEQ7
// (still fucking slow...)
void ReadAudio() {
        digitalWrite(MSGEQ7_RESET_PIN, HIGH);
        digitalWrite(MSGEQ7_RESET_PIN, LOW);
        for (byte band = 0; band < 7; band++) {
                digitalWrite(MSGEQ7_STROBE_PIN, LOW);
                delayMicroseconds(30);
                left[band] = analogRead(AUDIO_LEFT_PIN);
                right[band] = analogRead(AUDIO_RIGHT_PIN);
                digitalWrite(MSGEQ7_STROBE_PIN, HIGH);
        }
}

void ReadAudio2() {
        digitalWrite(MSGEQ7_RESET_PIN, HIGH);
        digitalWrite(MSGEQ7_RESET_PIN, LOW);
        for (byte band = 0; band < 7; band++) {
                digitalWrite(MSGEQ7_STROBE_PIN, LOW);
                delayMicroseconds(30);
                left[band] = analogRead(AUDIO_LEFT_PIN) / 4;
                right[band] = analogRead(AUDIO_RIGHT_PIN) / 4;
                digitalWrite(MSGEQ7_STROBE_PIN, HIGH);
        }
}`

-------------------------------------

`//amqttCallBack
// mainly following this code: https://github.com/marvinroger/async-mqtt-client/blob/master/examples/FullyFeatured-ESP8266/FullyFeatured-ESP8266.ino

void connectToWifi() {
  //WiFi.mode(WIFI_AP_STA);
  Serial.println("Connecting to Wi-Fi...");
  //WiFi.begin("ssid","pass",8);         // Arranca modo station
  //Serial.print("wifimode: " );//Debug
  //Serial.println(WiFi.getMode());//Debug

}

void onWifiConnect(const WiFiEventStationModeGotIP& event) {
  Serial.println("Connected to Wi-Fi.");
  connectToMqtt();
}

void onWifiDisconnect(const WiFiEventStationModeDisconnected& event) {
  Serial.println("Disconnected from Wi-Fi.");
  mqttReconnectTimer.detach(); // ensure we don't reconnect to MQTT while reconnecting to Wi-Fi
  wifiReconnectTimer.once(2, connectToWifi);
}

void connectToMqtt() {
  Serial.println("Connecting to MQTT...");
  mqttClient.connect();
}

void onMqttConnect(bool sessionPresent) {
        Serial.println("Connected to MQTT.");
        Serial.print("Session present: ");
        Serial.println(sessionPresent);
        uint16_t packetIdSub = mqttClient.subscribe(led_vertical_set_topic, 1);
        Serial.print("Subscribing at QoS 1, packetId: ");
        Serial.println(packetIdSub);
        sendState();
        Serial.println("Publishing at QoS 1");
        // uint16_t packetIdPub1 = mqttClient.publish("test/lol", 1, true, "test 2");
        // Serial.print("Publishing at QoS 1, packetId: ");
        // Serial.println(packetIdPub1);
        // uint16_t packetIdPub2 = mqttClient.publish("test/lol", 2, true, "test 3");
        // Serial.print("Publishing at QoS 2, packetId: ");
        // Serial.println(packetIdPub2);
}

void onMqttDisconnect(AsyncMqttClientDisconnectReason reason) {
  Serial.println("Disconnected from MQTT.");

  if (WiFi.isConnected()) {
    mqttReconnectTimer.once(2, connectToMqtt);
  }
}

void onMqttSubscribe(uint16_t packetId, uint8_t qos) {
        Serial.println("Subscribe acknowledged.");
        Serial.print("  packetId: ");
        Serial.println(packetId);
        Serial.print("  qos: ");
        Serial.println(qos);
}

void onMqttUnsubscribe(uint16_t packetId) {
        Serial.println("Unsubscribe acknowledged.");
        Serial.print("  packetId: ");
        Serial.println(packetId);
}

void onMqttMessage(char* topic, char* payload, AsyncMqttClientMessageProperties properties, size_t len, size_t index, size_t total) {
        Serial.println("Publish received.");
        Serial.print("  topic: ");
        Serial.println(topic);
        Serial.print("  qos: ");
        Serial.println(properties.qos);
        Serial.print("  dup: ");
        Serial.println(properties.dup);
        Serial.print("  retain: ");
        Serial.println(properties.retain);
        Serial.print("  len: ");
        Serial.println(len);
        Serial.print("  index: ");
        Serial.println(index);
        Serial.print("  total: ");
        Serial.println(total);

        char message[len + 1];
        for (int i = 0; i < len; i++) {
                message[i] = (char)payload[i];
        }
        message[len] = '\0';
        Serial.println(message);

        if (!processJson(message)) {
                return;
        }

}

void onMqttPublish(uint16_t packetId) {
        Serial.println("Publish acknowledged.");
        Serial.print("  packetId: ");
        Serial.println(packetId);
}

/********************************** START SEND STATE*****************************************/
void sendState() {
        StaticJsonBuffer<BUFFER_SIZE> jsonBuffer;

        JsonObject& root = jsonBuffer.createObject();
        // Step 2: Build object tree in memory
        root["state"] = (stateOn) ? on_cmd : off_cmd;
        JsonObject& color = root.createNestedObject("color");
        color["r"] = red;
        color["g"] = green;
        color["b"] = blue;

        root["brightness"] = myBrightness;
        root["effect"] = effectString.c_str();

        char buffer[root.measureLength() + 1];
        root.printTo(buffer, sizeof(buffer));

        mqttClient.publish(led_vertical_state_topic,1, true, buffer);
}

/********************************** START PROCESS JSON*****************************************/
bool processJson(char* message) {
        StaticJsonBuffer<BUFFER_SIZE> jsonBuffer;

        JsonObject& root = jsonBuffer.parseObject(message);

        if (!root.success()) {
                Serial.println("parseObject() failed");
                return false;
        }
// verify if state= on_cmd if string compare are equal result is =0
        if (root.containsKey("state")) {
                if (strcmp(root["state"], on_cmd) == 0) {
                        stateOn = true;
                }
                else if (strcmp(root["state"], off_cmd) == 0) {
                        stateOn = false;

                }
        }

        //  modificar segun la estructura del mensaje mqtt

        oldeffectString = effectString;

        if (root.containsKey("brightness")) {
                myBrightness = root["brightness"];
        }
        else {
                myBrightness = brightness;
        }

        if (root.containsKey("color")) {
                red = root["color"]["r"];
                green = root["color"]["g"];
                blue = root["color"]["b"];
        }
        else {
                // Red = red;
                // Green = green;
                // Blue = blue;
        }

        if (root.containsKey("effect")) {
                effect = root["effect"];
                opMode = root["effect"];
                effectString = effect;
                //  gCurrentPatternNumber = getposition();
                //twinklecounter = 0; //manage twinklecounter
        }

        //flash = true;
        //startFlash = true;

        return true;
}
`

**Comment by luebbe** [comment] 2021-02-10 20:48
Possible duplicate of #106

**Comment by bertmelis** [comment] 2021-07-26 11:42
Please provide a **minimal** example of the problem you face.

Closing for now, feel free to reopen.

**Closed by bertmelis** 2021-07-26 11:42 UTC
