### ISSUE TITLE
setWill() cause mqtt could not connect with SSL enable

### ISSUE THREAD

**Issue by dzungpv** [marvinroger/async-mqtt-client#107] opened 2018-07-20 08:34 UTC
I am switch from PubSubClient becasue it block cpu. But i have a problem.
I enable SSL by change ASYNC_TCP_SSL_ENABLED to 1.
Then i set this line:
```
mqttClient.setWill(MQTT_LIGHT_AVAILABILITY_TOPIC, 0, true, MQTT_LIGHT_AVAILABILITY_LWTMESSAGE);
```
after 
```
mqttClient.setServer(MQTT_HOST, MQTT_PORT);
```
But it will not connect to my server, remove the line it connected.

I have try to setWill() in onMqttConnect() but it not work.

**Comment by rneurink** [comment] 2018-08-25 14:55
I am also having this problem. I can connect over SSL perfectly but when using the SetWill command it will not connect with an disconnect with reason 0

**Comment by bertmelis** [comment] 2018-09-02 21:54
I'm working without SSL but can't connect after `setWill`. After commenting out, it works just fine!

**Comment by bertmelis** [comment] 2018-09-02 22:14
I figured out my problem. AsyncMqttClient doesn't copy the last will *topic* or *value* but only saves a pointer. And after `setWill` is called, *topic* and *value* might get out of scope.

I've marked made topic and payload `static` to keep them available for when the mqtt connection is established (which is async and not in the same scope as `setWill`).

**Comment by rneurink** [comment] 2018-09-04 15:19
@bertmelis 
Could you post your code? I still seem to have the problem
This is my code https://pastebin.com/T4e9Ezc8

**Comment by bertmelis** [comment] 2018-09-04 15:27
You're using mosquitto? What does the log of your broker say?

**Comment by rneurink** [comment] 2018-09-04 16:33
1536078725: Socket error on client <unknown>, disconnecting.
1536078725: New connection from 192.168.0.107 on port 8883.
It is kind of weird how it tries to connect twice just after each other

**Comment by bertmelis** [comment] 2018-09-04 17:43
Without SSL it is working? It sure seems like some buffer got overwritten.

**Comment by rneurink** [comment] 2018-09-04 17:47
It is working without SSL and it is working without the `mqttClient.setWill`

**Comment by rneurink** [comment] 2018-09-04 17:59
This is definitely a bug in my code, mosquitto SSL or the lib. After reflashing this multiple times I get around 50% succeeded connections with working will

**Comment by sooyewguan** [comment] 2018-09-12 11:19
Same problem, setwill doesn't work with SSL

**Comment by timpur** [comment] 2018-09-13 21:52
Sadly ATM I lack time to investigate, but I will try to... When I can

**Comment by sooyewguan** [comment] 2018-12-23 13:57
Try change the lwIP to v2 Higher Bandwidth

**Comment by jeroenst** [comment] 2018-12-23 19:37
My error was caused because the setwill function doesn't copy the *topic data but just stores the pointer. Because I called this from a separate mqttinit function, the topic was lost because the variable containing the topic was not static. So it was a different error which has nothing to do with SSL. Altough, when using setwill in combination with ssl the connection fails with also the same error in the mosquitto logging.

**Comment by jeroenst** [comment] 2018-12-23 19:44
With ssl enabled I get this error:

`(connectToMqtt) Connecting mqtt

Exception (29):
epc1=0x4021d770 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000204 depc=0x00000000

ctx: sys 
sp: 3fffe5a0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffe740:  0d31f0e0 0b204f19 eef326de 3fff186c  
3fffe750:  3fffba74 00000408 3fffba74 40100698  
3fffe760:  00000204 4022c0ca 00009c10 00001382  
3fffe770:  00000082 3fffb81c 3fffbda4 4022c2e0  
3fffe780:  fed37fa0 00000000 00000001 00000001  
3fffe790:  3fffb81c 00000082 3fffba5c 4022c0ca  
3fffe7a0:  3fffb81c 3fffba5c 00000081 4022cdca  
3fffe7b0:  3fff186c 000013c3 000013c3 4010020c  
3fffe7c0:  3fffbda4 3fffbc7c 00000040 00000000  
3fffe7d0:  0000000c 3fffb02c 00000041 00000041  
3fffe7e0:  00000000 00000001 00000001 4022c358  
3fffe7f0:  3fffb93c 3fffb02c 00000000 0000007f  
3fffe800:  3fffba5c 00000081 3fffba5c 0000007f  
3fffe810:  3fffba5c 3fffb02c 3fffb02c 4022d08d  
3fffe820:  00000002 00000001 3fffecac 4022c170  
3fffe830:  00000100 00000100 3fffb714 3fffb08c  
3fffe840:  3fffb2c4 00000100 3fffb02c 4022e249  
3fffe850:  3fffb714 3fff7e7c 00000003 40231ebd  
3fffe860:  00000002 00000079 00000003 00000000  
3fffe870:  00000100 3fff8e5b 3fffecac 40232359  
3fffe880:  3fff7e7c 3fffb714 3ffeb482 402321e5  
3fffe890:  3fffb284 0000001a 00000003 40232086  
3fffe8a0:  4022a214 3fffb284 3fff8e5b 00000000  
3fffe8b0:  00000004 3fffb284 3fff8e5b 4022a2fe  
3fffe8c0:  000005c0 00000000 a9daf112 91b0ba62  
3fffe8d0:  3ad1d3b7 96826b9b bc5709a4 ba59846e  
3fffe8e0:  82ae2911 14513370 a3c7201e 6dc7c908  
3fffe8f0:  dbbca0f4 0e2c7be9 ed7781d0 ddab3bad  
3fffe900:  8d5bad12 0000801c 00000000 00000000  
3fffe910:  00000000 00000000 00000000 00000000  
3fffe920:  00000000 e82c0000 00000000 ffffff80  
3fffe930:  3fffea00 3fffe9f0 0000000c 00000006  
3fffe940:  3ffea152 00000007 00000000 4024eeff  
3fffe950:  00000000 0000000b 402524b8 00000000  
3fffe960:  3fff1430 3fff1330 3fff1474 402185a0  
3fffe970:  3fff1481 00000002 7ffffff2 ffff0208  
3fffe980:  3fff1474 7fffffff 00000001 3ffefd5c  
3fffe990:  3fff186c 000007f5 000007f5 3fff186c  
3fffe9a0:  00000010 00000010 00000000 3fff186c  
3fffe9b0:  00000010 00000010 00000000 40100579  
3fffe9c0:  3fff186c 40213b83 000007f4 3fff186c  
3fffe9d0:  00000010 00000010 00000000 40100579  
3fffe9e0:  00000010 40213b83 3fff1268 00000000  
3fffe9f0:  00000010 3fff1118 3fff1118 40213b83  
3fffea00:  3ffe9bd8 00000000 3fff1118 3ffefd5c  
3fffea10:  00000010 3fff10a0 3fff10a0 40213b83  
3fffea20:  3ffe9bd8 00000000 3fff10a0 40213bcf  
3fffea30:  3ffe9bd8 3ffe9bd8 3fff10a0 40213c01  
3fffea40:  3fff0a6c 3fff0a98 3fff10a0 40213c4e  
3fffea50:  3ffe9bd8 402068c8 3fff15b8 4020f400  
3fffea60:  00000000 00000000 00000001 40214b45  
3fffea70:  4000b570 3fff0a98 3ffeb55c 40214b7e  
3fffea80:  00000000 00000000 00000000 00000000  
3fffea90:  00000000 00000000 00000000 00000000  
3fffeaa0:  00000000 00000000 00000000 00000000  
3fffeab0:  00000000 00000000 00000000 00000000  
3fffeac0:  00000000 00000000 00000000 00000000  
3fffead0:  00000000 00000000 00000000 00000000  
3fffeae0:  00000000 00000000 00000000 00000000  
3fffeaf0:  00000000 00000000 40244677 00000001  
3fffeb00:  ffffffff 00000000 3ffeb951 00000008  
3fffeb10:  402446c6 3ffeef98 3fff1f3c 00000001  
3fffeb20:  402447d2 3ffeef98 3fff1f3c 3ffeef98  
3fffeb30:  00000002 00000000 00000020 40100f22  
3fffeb40:  3ffeb802 40104304 3ffeef98 00000001  
3fffeb50:  00000001 40103523 3ffef9c8 00000008  
3fffeb60:  40103986 3ffeef70 3fff1f3c 00000001  
3fffeb70:  402447d2 3ffeef70 3fff1f3c 3ffeef70  
3fffeb80:  4010346a 00000028 7fffffff 00000002  
3fffeb90:  00000140 00000000 46eb681a fd79959c  
3fffeba0:  74a394a0 d0b4c507 f26044f0 52b74681  
3fffebb0:  78c0d29f 5b589172 568ea684 8f07d5b7  
3fffebc0:  3a5473d2 97bfe564 a93d5976 b2a1a2ed  
3fffebd0:  59147f37 ef02a022 010302bb 00800100  
3fffebe0:  00000000 00000000 00000000 00000000  
3fffebf0:  00000000 30090000 3f80cf16 d9433b92  
3fffec00:  b63a0a02 fe270b60 c19a8bb1 00000000  
3fffec10:  00000000 00000000 00000000 00000000  
3fffec20:  00000000 00000000 00000000 00000000  
3fffec30:  00000000 00000000 00000000 00000000  
3fffec40:  00000000 00000000 00000000 00000000  
3fffec50:  00000000 3ffe0000 12f1daa9 62bab091  
3fffec60:  b7d3d13a 9b6b8296 a40957bc 6e8459ba  
3fffec70:  1129ae82 70335114 00000020 40100f22  
3fffec80:  3ffeb802 4024377f 3ffeef98 3fff867c  
3fffec90:  00000000 40236bb3 000001f0 0000021d  
3fffeca0:  0000039a 00000002 00000496 00000201  
3fffecb0:  00000382 401049a3 3fff867c 3fff2304  
3fffecc0:  000000db 3fff23f8 0000039a 0000000c  
3fffecd0:  00000000 00000000 3fff19a0 00000b00  
3fffece0:  40227eec 00000008 00000002 00000001  
3fffecf0:  3fff23f8 3fff8799 000006c2 40227db5  
3fffed00:  00000b51 3fff86bc 00000b58 3fff23f4  
3fffed10:  3fff72e4 00000007 00820011 3fff8710  
3fffed20:  00000496 816e4939 8d530449 4e2b2939  
3fffed30:  88f47582 3fffa324 370b9167 00000b58  
3fffed40:  3fff8799 00000b58 3fff86bc 40229552  
3fffed50:  9101c482 1a26b1f4 c9123a0a 69ceec6a  
3fffed60:  7755ef3e 000011a1 000011a1 4010020c  
3fffed70:  0000002b 3fff92cc 3fff92cc 3fffa324  
3fffed80:  00000000 00000ae5 3fff7e84 402014c6  
3fffed90:  3fff91bd 3fffa9e4 0000000d 00000b58  
3fffeda0:  3fff8799 00000b58 3fff86bc 00000b58  
3fffedb0:  3fff8799 00000b58 3fff86bc 40228f9c  
3fffedc0:  00000002 00000000 00000020 40100f22  
3fffedd0:  3ffeb802 40104304 3ffeef70 40226760  
3fffede0:  00000001 40103523 3ffef9c8 3fffa9cc  
3fffedf0:  3fffee40 0000000b 00000010 40226134  
3fffee00:  40103269 00040000 7fffffff 01000000  
3fffee10:  3fffee40 3fffa9e4 3fff86bc 40229104  
3fffee20:  3ffef9c8 40102192 00000000 3fff842c  
3fffee30:  00000000 3fffa9e4 3fff7e84 4020129d  
3fffee40:  00000000 00000000 4bc6a7f0 00000000  
3fffee50:  3fffee60 40101fe8 40106576 ee978d4f  
3fffee60:  00000000 00000030 00000010 00000001  
3fffee70:  3fff1330 3fff1be0 3fffa9e4 4020b30b  
3fffee80:  3fff842c 00000001 00000000 fffffffe  
3fffee90:  ffffffff 3fffc6fc 00000001 3fff1bfc  
3fffeea0:  3fff842c 3fff1be0 3fff1bdc 4020b334  
3fffeeb0:  3fff842c 3fff1be0 3fff1be1 40221f90  
3fffeec0:  9902a8c0 00000000 00000000 00000000  
3fffeed0:  00000000 40226760 00000184 3fffaa02  
3fffeee0:  3fff1d58 3fffa9e4 3fff1e40 40225eed  
3fffeef0:  00000014 00000a90 00000a90 3fff1d58  
3fffef00:  3fffdc80 3fff2304 3fff72e4 3fff2374  
3fffef10:  00000008 3fff1d58 3fffa9e4 4021f3a0  
3fffef20:  3fffdc80 3fff2304 3fff72e4 4021f1db  
3fffef30:  40248612 3fff2304 3fff72e4 40248623  
3fffef40:  3fffa9f4 3fffa9e4 3fffdab0 3ffe8624  
3fffef50:  40243513 00000000 3fff72e4 4024a587  
3fffef60:  40000f49 3fffdab0 3fffdab0 40000f49  
3fffef70:  40000e19 40001878 00000002 00000000  
3fffef80:  3fffff10 aa55aa55 000000a0 40104424  
3fffef90:  4010442a 00000002 00000000 a30ef3a6  
3fffefa0:  4010000d 52ece56e 941144b8 a22b85d8  
3fffefb0:  00000000 3fffef4c 00000000 3fffff58  
3fffefc0:  3fffffd0 00000000 00000000 feefeffe  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
3ffff000:  feefeffe feefeffe feefeffe feefeffe  
3ffff010:  feefeffe feefeffe feefeffe feefeffe  
3ffff020:  feefeffe feefeffe feefeffe feefeffe  
3ffff030:  feefeffe feefeffe feefeffe feefeffe  
3ffff040:  feefeffe feefeffe feefeffe feefeffe  
3ffff050:  feefeffe feefeffe feefeffe feefeffe  
3ffff060:  feefeffe feefeffe feefeffe feefeffe  
3ffff070:  feefeffe feefeffe feefeffe feefeffe  
3ffff080:  feefeffe feefeffe feefeffe feefeffe  
3ffff090:  feefeffe feefeffe feefeffe feefeffe  
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff100:  feefeffe feefeffe feefeffe feefeffe  
3ffff110:  feefeffe feefeffe feefeffe feefeffe  
3ffff120:  feefeffe feefeffe feefeffe feefeffe  
3ffff130:  feefeffe feefeffe feefeffe feefeffe  
3ffff140:  feefeffe feefeffe feefeffe feefeffe  
3ffff150:  feefeffe feefeffe feefeffe feefeffe  
3ffff160:  feefeffe feefeffe feefeffe feefeffe  
3ffff170:  feefeffe feefeffe feefeffe feefeffe  
3ffff180:  feefeffe feefeffe feefeffe feefeffe  
3ffff190:  feefeffe feefeffe feefeffe feefeffe  
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff200:  feefeffe feefeffe feefeffe feefeffe  
3ffff210:  feefeffe feefeffe feefeffe feefeffe  
3ffff220:  feefeffe feefeffe feefeffe feefeffe  
3ffff230:  feefeffe feefeffe feefeffe feefeffe  
3ffff240:  feefeffe feefeffe feefeffe feefeffe  
3ffff250:  feefeffe feefeffe feefeffe feefeffe  
3ffff260:  feefeffe feefeffe feefeffe feefeffe  
3ffff270:  feefeffe feefeffe feefeffe feefeffe  
3ffff280:  feefeffe feefeffe feefeffe feefeffe  
3ffff290:  feefeffe feefeffe feefeffe feefeffe  
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff300:  feefeffe feefeffe feefeffe feefeffe  
3ffff310:  feefeffe feefeffe feefeffe feefeffe  
3ffff320:  feefeffe feefeffe feefeffe feefeffe  
3ffff330:  feefeffe feefeffe feefeffe feefeffe  
3ffff340:  feefeffe feefeffe feefeffe feefeffe  
3ffff350:  feefeffe feefeffe feefeffe feefeffe  
3ffff360:  feefeffe feefeffe feefeffe feefeffe  
3ffff370:  feefeffe feefeffe feefeffe feefeffe  
3ffff380:  feefeffe feefeffe feefeffe feefeffe  
3ffff390:  feefeffe feefeffe feefeffe feefeffe  
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff400:  feefeffe feefeffe feefeffe feefeffe  
3ffff410:  feefeffe feefeffe feefeffe feefeffe  
3ffff420:  feefeffe feefeffe feefeffe feefeffe  
3ffff430:  feefeffe feefeffe feefeffe feefeffe  
3ffff440:  feefeffe feefeffe feefeffe feefeffe  
3ffff450:  feefeffe feefeffe feefeffe feefeffe  
3ffff460:  feefeffe feefeffe feefeffe feefeffe  
3ffff470:  feefeffe feefeffe feefeffe feefeffe  
3ffff480:  feefeffe feefeffe feefeffe feefeffe  
3ffff490:  feefeffe feefeffe feefeffe feefeffe  
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  feefeffe feefeffe feefeffe feefeffe  
3ffff950:  feefeffe feefeffe feefeffe feefeffe  
3ffff960:  feefeffe feefeffe feefeffe feefeffe  
3ffff970:  feefeffe feefeffe feefeffe feefeffe  
3ffff980:  feefeffe feefeffe feefeffe feefeffe  
3ffff990:  feefeffe feefeffe feefeffe feefeffe  
3ffff9a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9f0:  feefeffe feefeffe feefeffe feefeffe  
3ffffa00:  feefeffe feefeffe feefeffe feefeffe  
3ffffa10:  feefeffe feefeffe feefeffe feefeffe  
3ffffa20:  feefeffe feefeffe feefeffe feefeffe  
3ffffa30:  feefeffe feefeffe feefeffe feefeffe  
3ffffa40:  feefeffe feefeffe feefeffe feefeffe  
3ffffa50:  feefeffe feefeffe feefeffe feefeffe  
3ffffa60:  feefeffe feefeffe feefeffe feefeffe  
3ffffa70:  feefeffe feefeffe feefeffe feefeffe  
3ffffa80:  feefeffe feefeffe feefeffe feefeffe  
3ffffa90:  feefeffe feefeffe feefeffe feefeffe  
3ffffaa0:  feefeffe feefeffe feefeffe feefeffe  
3ffffab0:  feefeffe feefeffe feefeffe feefeffe  
3ffffac0:  feefeffe feefeffe feefeffe feefeffe  
3ffffad0:  feefeffe feefeffe feefeffe feefeffe  
3ffffae0:  feefeffe feefeffe feefeffe feefeffe  
3ffffaf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffb00:  feefeffe feefeffe feefeffe feefeffe  
3ffffb10:  feefeffe feefeffe feefeffe feefeffe  
3ffffb20:  feefeffe feefeffe feefeffe feefeffe  
3ffffb30:  feefeffe feefeffe feefeffe feefeffe  
3ffffb40:  feefeffe feefeffe feefeffe feefeffe  
3ffffb50:  feefeffe feefeffe feefeffe feefeffe  
3ffffb60:  feefeffe feefeffe feefeffe feefeffe  
3ffffb70:  feefeffe feefeffe feefeffe feefeffe  
3ffffb80:  feefeffe feefeffe feefeffe feefeffe  
3ffffb90:  feefeffe feefeffe feefeffe feefeffe  
3ffffba0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbb0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbc0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbd0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbe0:  00000005 00000000 00000020 40100f22  
3ffffbf0:  3ffeb805 4010431f 3ffef268 feefeffe  
3ffffc00:  40101c3d 3ffef268 feefeffe feefeffe  
3ffffc10:  0000000f 00018579 3ffefcf0 40101e0e  
3ffffc20:  3ffec08c 00000000 00000000 4021c0dc  
3ffffc30:  0000000f 00018579 4010224e 00000100  
3ffffc40:  3ffeb805 4010431f 3ffef240 00000001  
3ffffc50:  40101c3d 3ffef240 feefeffe 4021c0dc  
3ffffc60:  0000000f 3ffffd53 3ffefcf0 40101e0e  
3ffffc70:  3ffec098 3ffffd63 00000000 4021c0dc  
3ffffc80:  00000000 00000000 0000001f 40104bfd  
3ffffc90:  4000050c 3ffffd83 3ffef218 4021c0dc  
3ffffca0:  40102cc8 00000030 00000019 fffffffe  
3ffffcb0:  40101bef 00000008 00000000 3ffec08c  
3ffffcc0:  00000001 00382c33 0000000f 00000050  
3ffffcd0:  3ffefcf0 3ffffdc3 00000000 3ffec08c  
3ffffce0:  00000001 3ffec08c 3ffefcf0 4021c0dc  
3ffffcf0:  3ffffe20 3ffe8308 3ffffd80 40217999  
3ffffd00:  3ffe8308 3ffffdc2 3ffffd30 4021c0dc  
3ffffd10:  3ffffe40 3ffe8308 3ffffda0 3ffffd80  
3ffffd20:  4021c0dc 3ffffe20 3ffffdc2 40217d54  
3ffffd30:  00000001 00000000 3ffffdda 000000ff  
3ffffd40:  0000005c 00000001 4010426a 3ffef9c8  
3ffffd50:  3ffef950 4010431f 3ffef240 000000fc  
3ffffd60:  40101c3d 3ffef240 4010426a 3ffef9c8  
3ffffd70:  40103e6f 3ffef9c8 3ffefcf0 00000100  
3ffffd80:  0000005c 401037de 3ffef9c8 000000ff  
3ffffd90:  00000005 00000000 00000020 40100f22  
3ffffda0:  3ffeb805 4010431f 3ffef240 00000002  
3ffffdb0:  40101c3d 3ffef240 7fffffff 000000fe  
3ffffdc0:  00007fff 00573e1f 3ffefcf0 40101e0e  
3ffffdd0:  3ffec080 00000000 00000000 00000002  
3ffffde0:  00007fff 00573e1f 4010224e 00000100  
3ffffdf0:  7fffffff 3ffec080 3ffec080 00000001  
3ffffe00:  00000001 00004a88 00040000 4000050c  
3ffffe10:  402153d6 00573e1f 53002200 4000050c  
3ffffe20:  3fffc278 40101fe8 3fffc200 00000022  
3ffffe30:  3ffec08c 00000000 00000000 fffffffe  
3ffffe40:  40104ffb 00000030 00000010 ffffffff  
3ffffe50:  40106522 3ff20a00 00000000 40100721  
3ffffe60:  00000000 00000000 00000000 fffffffe  
3ffffe70:  ffffffff 3fffc6fc 00000001 3fff10d4  
3ffffe80:  3fff10e8 3fffdad0 3fff196c 00000030  
3ffffe90:  00000000 00000000 00000001 3fff1965  
3ffffea0:  3fff1278 3fffdad0 3fff196c 00000030  
3ffffeb0:  40000ea3 00000000 00000001 00000001  
3ffffec0:  3fffdab0 00000000 3fffd9d0 3fff196c  
3ffffed0:  00000000 00000000 00000001 3fff1965  
3ffffee0:  00000000 3fffdad0 3fff196c 00000030  
3ffffef0:  00000000 00000000 3fff1278 40215360  
3fffff00:  00000000 4bc6a7f0 00001655 3fff196c  
3fffff10:  00000000 00000000 4bc6a7f0 00000000  
3fffff20:  3fff0ac0 00000000 40106576 a3126e97  
3fffff30:  00000000 00000000 00000000 40215eb0  
3fffff40:  3fffdad0 3fff10e8 3fff10d4 4020489e  
3fffff50:  4024c20e 3fff1278 3ffe8624 3fff1278  
3fffff60:  3fffdad0 3fff196c 40214b24 3fffefb0  
3fffff70:  00000000 00000000 3fff1965 3fff196c  
3fffff80:  3fffdad0 3fff1278 3fff1965 40205c14  
3fffff90:  00000000 00000000 00000000 00000000  
3fffffa0:  00000000 00000000 00000001 40214b45  
<<<stack<<<

last failed alloc call: 4022C0CA(1032)
`

**Comment by Bastelralf** [comment] 2019-09-21 10:30
Hi 
is there a workaround to get setwill() with SSL working?

**Comment by Plggeldy** [comment] 2019-09-21 10:59
I would love to know, what I can do for MQTTClient::setwill() with TLS/SSL.. 

Is there a chance to get it working?

**Comment by Plggeldy** [comment] 2019-09-24 06:27
The solution is here:

https://github.com/256dpi/arduino-mqtt

> Set a will message (last testament) that gets registered on the broker after connecting. setWill() has to be called before calling connect():<

**Comment by jeroenst** [comment] 2019-11-01 14:00
> The solution is here:
> 
> https://github.com/256dpi/arduino-mqtt
> 
> > Set a will message (last testament) that gets registered on the broker after connecting. setWill() has to be called before calling connect():<

Is this really non-blocking asynchronous?

**Comment by jeroenst** [comment] 2019-11-01 14:39
I did some investigation, it seems that the password is not send after the username (I receive everything up to the password with ncat). Very strange..

**Comment by KrYpToDeN** [comment] 2020-06-04 13:46
> The problem is that the _onconnect function calls _client.add for each piece of data to send to the mqtt server. When setwill is used, there is to much data to be send by the ASyncTCP module because it also add ssl data to each packet, causing it to drop the password.
> 
> After changing the code to send less packets setwill works with SSL!

Could you help me, how send less packets?
Our problem is the same - https://github.com/eclipse/mosquitto/issues/1715

**Comment by qcasey** [comment] 2020-06-04 14:30
I believe this is ultimately caused by #193. What I've done to get SSL working is implementing a queue and only allowing the packet in the head to be on the wire at any time.

This requires QoS2 and popping packets once they're acknowledged

**Comment by KrYpToDeN** [comment] 2020-06-05 13:56
> I believe this is ultimately caused by #193. What I've done to get SSL working is implementing a queue and only allowing the packet in the head to be on the wire at any time.
> 
> This requires QoS2 and popping packets once they're acknowledged

Hello.

Thank you for your answer, but it's for asynchronous code.

We use asynchronous version, because packets not so much to send/get.

But the problem is the same. Server got Will topic in mosquitto log file. But it publishes it 50/50 times. Also we can't find a way, when it's happed. It's always different. Will topic can go/it may be lost.

Do you know how solve it?

**Comment by bertmelis** [comment] 2021-02-10 11:18
The issue should be gone using the `development` branch.

**Closed by bertmelis** 2021-02-10 11:18 UTC
